---
- name: SETUP - setup configurations
  become: true
  hosts: localhost

  tasks:
  - name: Install sway apt
    ansible.builtin.apt:
      name: "{{ swaypacks }}"
    when: ansible_os_family == "Debian"

  - name: Install sway dnf
    ansible.builtin.dnf:
      pkg: "{{ swaypacks }}"
    when: 
      ansible_os_family == "RedHat" and sway_install == True

  - name: Install sway pacman
    community.general.pacman:
      name: "{{ swaypacks }}"
    when: ansible_os_family == "ArchLinux"

  - name: Additional packages
    ansible.builtin.package:
      name: "{{ packs }}"
    when: install_packages == True


  ### Copy some extra configuration stuff in common
  ### if `extra-configs` is true

  ### Copy sway-related configs, based on `type` var
  - name: Copy configs to ~/.config
    ansible.builtin.copy:
      src: "files/{{ type }}/"
      dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.config/"
      owner: "jacksonm"
      mode: '777'
  
  - name: Rust installation
    block:
      - name: Check if installed
        ansible.builtin.shell: command -v cargo
        register: cargo_exists
        ignore_errors: yes
      - name: Download Installer
        when: cargo_exists is failed
        get_url:
          url: https://sh.rustup.rs
          dest: /tmp/sh.rustup.rs
          mode: '0755'
          force: 'yes'
        tags:
          - rust
      - name: Install Rust/Cargo
        when: cargo_exists is failed
        shell: /tmp/sh.rustup.rs -y
        tags:
          - rust
    when: rust_install == True
