---
- name: SETUP - setup configurations
  become: true
  hosts: localhost

  tasks:
  - name: Install software apt
    ansible.builtin.apt: "{{ swaypacks }}"
    when: ansible_os_family == "Debian"

  - name: Install software dnf
    ansible.builtin.dnf:
      pkg: "{{ swaypacks }}"
    when: ansible_os_family == "RedHat"

  - name: Install software pacman
    community.general.pacman: "{{ swaypacks }}"
    when: ansible_os_family == "ArchLinux"


  ### Copy some extra configuration stuff in common
  ### if `extra-configs` is true 

  ### Copy sway-related configs, based on `type` var
  - name: Copy configs to ~/.config
    ansible.builtin.copy:
      src: "files/{{ type }}/"
      dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.config/"
      owner: "jacksonm"
      mode: '777'
      backup: yes